<?php
/**
 * @file
 * Code for the Blog feature.
 */

include_once 'crm_core_blog.features.inc';

/**
 * Implements hook_permission().
 */
function crm_core_blog_permission() {
  return array(
    'view crm core blog comment reports' => array(
      'title' => t('View CRM Core Blog reports'),
      'description' => t('View reports related to comment activity on blog posts.'),
    ),
  );
}

/**
 * Implements hook_crm_core_report_register().
 */
function crm_core_blog_crm_core_report_register() {
  $reports = array(
    'blogs' => array(
      'title'   => t('Blogs'),
      'reports' => array(
        'comment_overview' => array(
          'title'       => t('Post and comment overview'),
          'path'        => 'crm/reports/blog/overview',
          'description' => t('An overview of recent blog posts and comment activity.'),
        ),
        'comment_activity' => array(
          'title'       => t('Commenter activity report'),
          'path'        => 'crm/reports/blog/commenters',
          'description' => t('Details about the most active commenters on the blog.'),
        ),

        // @todo #11952 and #11954.
        'comment_authors' => array(
          'title'       => t('Blog author report'),
          'path'        => 'crm/reports/blog/commenters',
          'description' => t('Details about activity around posts from individual blog authors.'),
        ),
        'comment_topics' => array(
          'title'       => t('Comment topics report'),
          'path'        => 'crm/reports/blog/commenters',
          'description' => t('What topics are generating the most activity on the blog?'),
        ),
      ),
      'widgets' => array(),
    ),
  );

  return $reports;
}
