<?php

/**
 * Implementation of hook_deploy_aggregators().
 */
function deploy_aggregator_views_deploy_aggregators() {
  $path = drupal_get_path('module', 'deploy_aggregator_views') . '/plugins';
  return array(
    'DeployAggregatorViews' => array(
      'name' => 'Views aggregator',
      'description' => 'Aggregates content to a deployment plan by executing a user defined view.',
      'handler' => array(
        'class' => 'DeployAggregatorViews',
        'file' => 'DeployAggregatorViews.inc',
        'path' => $path,
      ),
    ),
  );
}
