<?php
/**
 * Warn about the soft dependency on system steam wrapper module
 */
function imagecache_actions_update_7001(&$sandbox) {
  //$t = get_t();
  drupal_set_message(t("Imagecache Actions: If you use the module:// notation anywhere in an image effect, you must now install the !module module.",
    array('!module' => l('System Stream Wrapper', 'http://drupal.org/project/system_stream_wrapper', array('external' => TRUE)))), 'warning');
}
