<?php
/**
 * @file
 * Code for the CRM Core Demo Settings feature.
 */

include_once 'crm_core_demo_settings.features.inc';

/**
 * Implements hook_date_formats().
 */
function crm_core_demo_settings_date_formats() {
  return array(
    array(
      'type' => 'date_format_slim',
      'format' => 'm/d/y',
      'locales' => array(),
    ),
    array(
      'type' => 'crm_core_month_year',
      'format' => 'M Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function crm_core_demo_settings_date_format_types() {
  return array(
    'date_format_slim' => t('Slim'),
    'crm_core_month_year' => t('Month and Year')
  );
}

/**
 * Implements hook_permission().
 */
function crm_core_demo_settings_permission() {
  return array(
    'view crm core reports' => array(
      'title' => t('View CRM Core reports'), 
    ),
  );
}
