  <?php
/**
 * @file
 * Code for the CRM Core Demo Settings feature.
 */

include_once 'crm_core_demo_settings.features.inc';

/**
 * Implements hook_date_formats().
 */
function crm_core_demo_settings_date_formats() {
  return array(
    array(
      'type' => 'date_format_slim',
      'format' => 'm/d/y',
      'locales' => array(),
    ),
    array(
      'type' => 'crm_core_month_year',
      'format' => 'M Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function crm_core_demo_settings_date_format_types() {
  return array(
    'date_format_slim' => t('Slim'),
    'crm_core_month_year' => t('Month and Year')
  );
}

/**
 * Implements hook_permission().
 */
function crm_core_demo_settings_permission() {
  return array(
    'view crm core reports' => array(
      'title' => t('View CRM Core reports'), 
    ),
  );
}

/**
 * Implementation of hook_library
 */
function crm_core_demo_settings_library() {
	
	// libraries for the basic interface
	// Helper functions for prototype inheritance - allows objects to be bound to jquery plug ins.
	$libraries['expanding'] = array(
    'title' => 'Expanding Textareas', 
    'website' => 'https://github.com/bgrins/ExpandingTextareas', 
    'version' => 1.15, 
    'js' => array(
			libraries_get_path('expanding') . '/expanding.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 0,
			),
		),
	);
	return $libraries;
}

/**
 * Page preprocessor
 */
function crm_core_demo_settings_preprocess_page($vars){
  
  // add autosize library for textareas
  // this should be on every page in the si  te
  drupal_add_library('crm_core_demo_settings', 'expanding');
  
}	


/*
 * Implementation of hook_menu_alter
 */
function crm_core_demo_settings_menu_alter(&$items) {

	// Sets the CRM Core dashboard tab to a preset homebox
	// this allows CRM Core to provide dashboards in a variety of situations
	// which could have varying business requirements
	$items['crm']['page callback'] = 'homebox_build';
	$items['crm']['page arguments'] = $items['crm/dashboard/hb']['page arguments'];
	
	// Sets the main contacts interface to use a different view
	// this allows us to work with the main contacts interface
	// without needing to change the default views crm core ships with
	
	// I think this gets overridden by views after I write it
	// going to need something else
	$items['crm/contacts']['page arguments'][0] = 'crm_core_contacts_alt';
	
}

function crm_core_demo_settings_views_bulk_operations_form_alter(&$form, &$form_state, &$vbo){
  
  // views bulk operations doesn't fit conveniently into the layout on some of the reports pages
  // it needs to be a little more intuitive for users
  // we are going to hide all the options available in the form
  // and make it part of a menu instead of a straight up form
  // this function probably belongs in the theme instead of this module
  // TODO: move this to the theme
  // TODO: make the button a drop down
  // TODO: create a script that handles the form submission when a link from a menu is selected
  if($form['#form_id'] == 'views_form_crm_core_contacts_alt_page_1'){
    
    if(isset($form['select']) && sizeof($form['select']['operation']['#options']) > 0){
      
      $options = array();
      $links = '';
      
      // construct the drop down button
      foreach ($form['select']['operation']['#options'] as $item => $val){
        $options[$item] = $val;
        if($item !== 0){
          $links .= '<li><a href="' . $item . '" class="vbo_action">' . $val . '</a></li>';
        }
      }
      
      $btn = <<<BTN
  <div class="btn-group vbo_btn_group">
    <a class="btn dropdown-toggle disabled btn-warning btn-small vbo_action_link pull-right" data-toggle="dropdown"  href="#">
    	<i class="icon-play-circle icon-white"></i> 
    	With Selected 
    	<span class="caret"></span>
    </a>
    <ul class="dropdown-menu pull-right vbo_btn_options">
  		$links
    </ul>
  </div>
BTN;

      $form['select']['#type'] = 'markup';
      $form['select']['#prefix'] = $btn . '<div class="vbo_actions_holder">';
      $form['select']['#suffix'] = '</div>';
    }

  }
    

  
}
