<?php
/**
 * @file
 * Code for the CRM Core Demo Settings feature.
 */

include_once 'crm_core_demo_settings.features.inc';

/**
 * Implements hook_date_formats().
 */
function crm_core_demo_settings_date_formats() {
  return array(
    array(
      'type' => 'date_format_slim',
      'format' => 'm/d/y',
      'locales' => array(),
    ),
    array(
      'type' => 'crm_core_month_year',
      'format' => 'M Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function crm_core_demo_settings_date_format_types() {
  return array(
    'date_format_slim' => t('Slim'),
    'crm_core_month_year' => t('Month and Year')
  );
}

/**
 * Implements hook_permission().
 */
function crm_core_demo_settings_permission() {
  return array(
    'view crm core reports' => array(
      'title' => t('View CRM Core reports'), 
    ),
  );
}

/**
 * Implementation of hook_library
 */
function crm_core_demo_settings_library() {
	
	// libraries for the basic interface
	// Helper functions for prototype inheritance - allows objects to be bound to jquery plug ins.
	$libraries['expanding'] = array(
    'title' => 'Expanding Textareas', 
    'website' => 'https://github.com/bgrins/ExpandingTextareas', 
    'version' => 1.15, 
    'js' => array(
			libraries_get_path('expanding') . '/expanding.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 0,
			),
		),
	);
	return $libraries;
}

/**
 * Page preprocessor
 */
function crm_core_demo_settings_preprocess_page($vars){
  
  // add autosize library for textareas
  drupal_add_library('crm_core_demo_settings', 'expanding');
  
}	