<?php

/**
 * Implementation of hook_menu().
 */
function deploy_ui_menu() {
  $items = array();

  $items['admin/structure/deploy'] = array(
    'title' => 'Deployment',
    'description' => 'Manage deployment plans, endpoints etc.',
    'page callback' => 'deploy_ui_overview_page',
    'access arguments' => array('administer deployments'),
    'file' => 'deploy_ui.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/structure/deploy/overview'] = array(
    'title' => 'Overview',
    'description' => 'Administrative overview over deployments',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -50,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function deploy_ui_theme() {
  return array(
    'deploy_ui_overview' => array(
      'variables' => array('blocks' => array()),
      'file' => 'deploy_ui.pages.inc',
    ),
    'deploy_ui_overview_plan_content' => array(
      'variables' => array('info' => array()),
      'file' => 'deploy_ui.pages.inc',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function deploy_ui_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}
