<?php

/**
 * Implements hook_install()
 */
function crm_core_news_install() {

  // Make sure sharethis is enabled for simplenews content type
  $sharethis_setting = variable_get('sharethis_node_option', '');

  $settings_array = explode(',', $sharethis_setting);

  if (array_search('simplenews', $settings_array) === FALSE) {
    $settings_array[] = 'simplenews';
    $sharethis_setting = implode(',', $settings_array);
    variable_set('sharethis_node_option', $sharethis_setting);
  }
}
