<?php
/**
 * @file
 * Code for the CRM Core News feature.
 */

include_once 'crm_core_news.features.inc';

/**
 * Implements hook_block_info().
 */
function crm_core_news_block_info() {
  $blocks['subscription'] = array(
    'info' => t('News digest subscription'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_core_news_block_view($delta = '') {
  global $user;

  if ($delta != 'subscription') {
    return array();
  }
  
  // Try to get related contact for user
  if (!empty($user->uid)) {
    $contact = crm_user_sync_get_contact_from_uid($user->uid);

    if ($contact) {
      $subscription = crm_core_news_subscription_load($contact);
    }
  }

  if (!empty($subscription)) {
    $content = t('You are already subscribed!');  
  }
  else {
    $profile = crm_core_profile_load('news_subscription');
    module_load_include('inc', 'crm_core_profile', 'crm_core_profile.forms');
    $form = drupal_get_form('crm_core_profile_entry_form', $profile);
 
    $content = $form;
  }

  return array(
    'subject' => t('Sign up for news alerts'),
    'content' => $content,
  );
}

/**
 * Implements hook_form_alter.
 */
function crm_core_news_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'crm_core_profile_entry_form' ||
          empty($form['profile_name']['#value']) ||
          $form['profile_name']['#value'] != 'news_subscription') {
    return;
  }

  $form['submit']['#value'] = t('Sign up');

  $form['#submit'][] = 'crm_core_news_subscription_form_submit';
}


/**
 * Submit handler on subscription.
 */
function crm_core_news_subscription_form_submit($form, $form_state) {
  crm_core_news_subscription_save($form_state['contact']);
}

/**
 * Loads crm core news subscription record.
 */
function crm_core_news_subscription_load($contact_id) { 
  if (is_object($contact_id)) {
    $contact_id = $contact_id->contact_id;
  }

  $query = db_select('crm_core_news_subscription', 's')
    ->fields('s')
    ->condition('contact_id', $contact_id);

  $result = $query->execute();

  return $result->fetchAssoc();
}

/**
 * Saves crm core news subscription record.
 */
function crm_core_news_subscription_save($contact_id, $settings = array()) {
  if (is_object($contact_id)) {
    $contact_id = $contact_id->contact_id;
  }

  $settings['contact_id'] = $contact_id;

  drupal_write_record('crm_core_news_subscription', $settings);
}
