<?php

/**
 * @file
 * Deploy Auto Plan module functions.
 */

/**
 * Implements hook_permission().
 */
function deploy_auto_plan_permission() {
  return array(
    'administer deploy plan auto' => array(
      'title' => t('Administer Automagic Deployment Plans'),
      'description' => t('Configure automagic deployment plans settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function deploy_auto_plan_menu() {
  $items = array();

  $items['admin/config/content/deploy-auto-plan'] = array(
    'title' => 'Automagic Deployment Plan',
    'description' => 'Administer automagic deployment plans',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_auto_plan_settings'),
    'access arguments' => array('administer deploy plan auto'),
  );

  return $items;
}

/**
 * Implements hook_entity_insert().
 */
function deploy_auto_plan_entity_insert($entity, $type) {
  _deploy_auto_plan_entity_save($entity, $type);
}

/**
 * Implements hook_entity_update().
 */
function deploy_auto_plan_entity_update($entity, $type) {
  _deploy_auto_plan_entity_save($entity, $type);
}

/* *
 * Implements hook_entity_delete()
 * /
// This isn't needed as it is handled by deploy.manager out of the box.
function deploy_auto_plan_entity_delete($entity, $type) {
}
*/

/**
 * Admin settings form.
 */
function deploy_auto_plan_settings($form, $form_state) {

  $plans = _deploy_auto_plan_plans_list();

  if (!count($plans)) {
    $msg = t('No deployment plans configured.');
    if (module_exists('deploy_ui') && user_access('administer deployments')) {
      $url = url('admin/structure/deploy/plans');
      $msg = t('No deployment plans configured. <a href="!url">Add a plan</a>.', array('!url' => $url));
    }
    return array('text' => array('#markup' => $msg));
  }

  $form['text'] = array(
    '#markup' => t('Select which deployment plan all modified entities should be added to.'),
  );

  $form['deploy_auto_plan_name'] = array(
    '#type' => 'select',
    '#title' => t('Plan'),
    '#empty_option' => t('- None -'),
    '#options' => $plans,
    '#default_value' => variable_get('deploy_auto_plan_name', NULL),
  );

  return system_settings_form($form);
}

/**
 * Handles an entity being saved.
 *
 * @param $entity
 *   The entity object.
 * @param $type
 *   The type of entity being updated (i.e. node, user, comment).
 */
function _deploy_auto_plan_entity_save($entity, $type) {
  $plan_name = variable_get('deploy_auto_plan_name', NULL);
  if (!$plan_name) {
    return;
  }

  $info = entity_get_info($type);
  if (empty($info['entity keys']['uuid'])) {
    // we only care about entities with UUIDs.
    return;
  }

  deploy_manager_add_to_plan($plan_name, $type, $entity);
}

 /**
 * Fetches a list of deployment plans.
 *
 * @return array
 *   The list of available plans.
 */
function _deploy_auto_plan_plans_list() {
  $options = array();
  $conditions = array('aggregator_plugin' => 'DeployAggregatorManaged');

  $plans = deploy_plan_load_all($conditions);
  foreach ($plans as $plan) {
    $options[$plan->name] = $plan->title;
  }

  return $options;
}
