<?php
/**
 * @file
 * Code for the CRM Core Donation feature.
 */

include_once('crm_core_donation.features.inc');

// @bug fix, prevent ajax error when switching payments
module_load_include('inc', 'crm_core_profile', 'crm_core_profile.forms');

/**
 * Implements hook_menu().
 */
function crm_core_donation_menu() {

  // default path for donation pages
  $items['donation_pages/%'] = array(
    'title' => 'Donate today',
    'page callback' => 'crm_core_donation_page_callback',
    'page arguments' => array(1),
    'access arguments' => array('access crm core donation page'),
    'file' => 'crm_core_donation.pages.inc',
    'type' => MENU_CALLBACK,
  );

  // donation widgets
  $items['donation_widgets/%'] = array(
    'title' => 'Donation widget',
    'page callback' => 'crm_core_donation_widget',
    'page arguments' => array(1),
    'access arguments' => array('access crm core donation page'),
    'file' => 'crm_core_donation.widget.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/crm/donation'] = array(
      'title' => 'Donation',
      'description' => 'Manage CRM Core Donation feature.',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('administer crm core donation'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/crm/donation/config'] = array(
    'title' => 'Donation settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_donation_config'),
    'access arguments' => array('administer crm core donation'),
  );

  $items['crm/donations/%'] = array(
    'title' => 'Edit donation page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_donation_page_form', 2, FALSE),
    'access arguments' => array('administer crm core donation'),
    'file' => 'crm_core_donation.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['crm/donations/%/delete'] = array(
    'title' => 'Delete donation page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_donation_page_delete_form', 2),
    'access arguments' => array('administer crm core donation'),
    'file' => 'crm_core_donation.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['crm/donations/new'] = array(
    'title' => 'Create new donation page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_donation_page_form'),
    'access arguments' => array('administer crm core donation'),
    'file' => 'crm_core_donation.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  // personal donation page
  $items['user/%user/pdp/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'crm_core_donation_pdp',
    'page arguments' => array(1, 'edit'),
    'access arguments' => array('create crm core donation PDP'),
    'file' => 'crm_core_donation.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/pdp/view'] = array(
    'title' => 'My donation page',
    'page callback' => 'crm_core_donation_pdp',
    'page arguments' => array(1),
    'access arguments' => array('create crm core donation PDP'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['user/%user/pdp'] = array(
    'title' => 'My donation page',
    'page callback' => 'crm_core_donation_pdp',
    'page arguments' => array(1),
    'access arguments' => array('create crm core donation PDP'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function crm_core_donation_permission() {
  return array(
    'administer crm core donation' => array(
      'title' => t('Administer CRM Core donation'),
      'description' => t('Administer CRM Core donation'),
    ),
    'access crm core donation page' => array(
      'title' => t('Access donation pages'),
      'description' => t('Ability to access donation pages and make online donations'),
    ),
    'create crm core donation PDP' => array(
      'title' => t('Create personal donation pages (PDP)'),
      'description' => t('Ability to create personal donation pages'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function crm_core_donation_theme() {
  return array(
    'crm_core_donation' => array(
      'render element' => 'form',
      //'function' => 'crm_core_donation_form_theme',
      'preprocess functions' => array('template_preprocess', 'crm_core_donation_form_theme_preprocess'),
      'template' => 'crm-core-donation-form',
    ),
  );
}

/*
 * Implements hook_commerce_line_item_type_info().
 */
function crm_core_donation_commerce_line_item_type_info() {

  $line_item_types['crm_core_donation'] = array(
    'name' => t('CRM Core Donation'),
    'description' => t('A CRM Core Donation'),
    'product' => FALSE,
    'add_form_submit_value' => t('Add donation'),
    'callbacks' => array(
      'configuration' => '_crm_core_donation_line_item_configuration',
      'title' => '_crm_core_donation_line_item_title',
      'add_form' => '_crm_core_donation_line_item_add_form',
      'add_form_submit' => '_crm_core_donation_line_item_add_form_submit',
    ),
  );

  return $line_item_types;
}

/**
 * Dispatch (callback) menu items for PDP
 *
 * @params
 *
 * (stdClass) $arg_user - $user object
 * (string) $render - edit/view
 *
 * @return
 *
 * A personal donation settings form
 * A personal donation page
 */
function crm_core_donation_pdp($arg_user, $render = 'view') {
  // check for PDP settings
  if (variable_get('crm_core_donation_pdp', 1) == 0) {
    return;
  }

  $crm_core_profile = variable_get('crm_core_donation_profile', '');
  if ($crm_core_profile != '') {
    module_load_include('inc', 'crm_core_profile', 'crm_core_profile.forms');
    $donation_profile = crm_core_profile_load($crm_core_profile);
    // load the PDP
    $data = array();
    $query = db_select('crm_core_donation_page', 'p')
    ->fields('p')
    ->condition('pdp', 1)
    ->condition('uid', $arg_user->uid);

    $result = $query->execute();
    $donation_page = $result->fetchAssoc();

    switch ($render) {
      case 'view':
      default:
        if (empty($donation_page)) {
          $link = l('click here', 'user/' . $arg_user->uid . '/pdp/settings');
          return '<div class="messages status">You have not created a personal donation page yet, ' . $link . ' to create it</div>';
        }
        $donation_profile['donation_page'] = $donation_page;
        return drupal_get_form('crm_core_profile_entry_form', $donation_profile);
      break;
      case 'edit':
        module_load_include('inc', 'crm_core_donation', 'crm_core_donation.pages');
        if (empty($donation_page)) {
          return drupal_get_form('crm_core_donation_page_form', NULL, TRUE);
        }
        return drupal_get_form('crm_core_donation_page_form', $donation_page['id'], TRUE);
      break;
    }
  }
  return drupal_access_denied();
}


/**
 * Page callback for system donation form
 *
 * @params
 * (int) $id    Donation page id
 *
 * @return
 * A fully rendered donation page or access denied
 */
function crm_core_donation_page_callback($id) {
  $crm_core_profile = variable_get('crm_core_donation_profile', '');
  if ($crm_core_profile != '') {
    module_load_include('inc', 'crm_core_profile', 'crm_core_profile.forms');
    $donation_profile = crm_core_profile_load($crm_core_profile);

    $donation_page = crm_core_donation_page_load($id);
    if (empty($donation_page)) {
      return drupal_access_denied();
    }

    if ($donation_page['status'] == 0) {
      return drupal_access_denied();
    }

    $donation_profile['donation_page'] = $donation_page;
    return drupal_get_form('crm_core_profile_entry_form', $donation_profile);
  }
  return drupal_access_denied();
}

/**
 * Configuration form
 */
function crm_core_donation_config($form, &$form_state) {

  $form['crm'] = array(
    '#type' => 'fieldset',
    '#title' => t('CRM Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $crm_core_profiles = crm_core_profile_load_all();
  $profile_options = array('' => t('--Select--'));
  foreach ($crm_core_profiles as $crm_core_profile) {
    $profile_options[$crm_core_profile['name']] = $crm_core_profile['label'];
  }

  // profile we will use to attach to the event
  $form['crm']['crm_core_donation_profile'] = array(
    '#type' => 'select',
    '#title' => 'Select the CRM Core profile to use for donations',
    '#options' => $profile_options,
    '#default_value' => variable_get('crm_core_donation_profile', ''),
    '#required' => TRUE,
  );

  // the billing address we need to map
  $profile_name = variable_get('crm_core_donation_profile', '');
  if ($profile_name != '') {

    $options = array('' => t('--select--'));
    $options = crm_core_donation_fields($profile_name);

    $form['crm']['crm_core_donation_billing_address'] = array(
      '#type' => 'select',
      '#title' => 'Billing address field',
      '#description' => t('Please choose the billing address field used'),
      '#options' => $options,
      '#default_value' => variable_get('crm_core_donation_billing_address', ''),
      '#required' => TRUE,
    );
  }

  $form['crm_core_donation_pdp'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable personal donation pages',
    '#default_value' => variable_get('crm_core_donation_pdp', 1),
  );

  $form['IMO'] = array(
    '#type' => 'fieldset',
    '#title' => t('Dedication notification settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['IMO']['crm_core_donation_imo_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Dedication e-mail message'),
    '#description' => t('The message you would like to send to the person you are honoring or dedicating, the following replacement values are available: !donor_name, !dedicant_name, !dedication_type, !donation_amount.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#default_value' => variable_get('crm_core_donation_imo_message', '')
  );

  $form['crm_core_donation_redirect_message'] = array(
    '#type' => 'textarea',
    '#title' => 'redirect message',
    '#description' => 'When someone successfully makes a donation, this message will be shown',
    '#default_value' => variable_get('crm_core_donation_redirect_message', 'Thank you for your donation'),
  );

  return system_settings_form($form);
}

/*
 * Implements hook_crm_core_profile_save().
 *
 * Send IHO/IMO email.
 */
function crm_core_donation_crm_core_profile_save($profile, $form_state_values) {

  if ($profile['name'] != 'donation') {
    return;
  }

  $v = $form_state_values;
  $dedication_type = $v['activity']['field_donation_dedication_type'][LANGUAGE_NONE][0]['value'];
  if (!isset($dedication_type) || !$dedication_type) {
    return;
  }

  $dedicant_email = $v['activity']['field_donation_dedication_email'][LANGUAGE_NONE][0]['email'];
  if ( !isset($dedicant_email) || $dedicant_email == '') {
    return;
  }

  $type = '';
  switch ($dedication_type) {
    case 'IHO':
    default:
      $type = 'in honor of';
    break;
    case 'IMO':
      $type = 'in memory of';
    break;
    case 'OBO':
      $type = 'on behalf of';
    break;
  }

  $replacement = array(
    '!donor_name' => implode(' ', $v['contact_name'][LANGUAGE_NONE][0]),
    '!dedicant_name' => $v['activity']['field_donation_dedication_name'][LANGUAGE_NONE][0]['value'],
    '!dedication_type' => $type,
    '!donation_amount' => $v['activity']['field_donation_amounts'][LANGUAGE_NONE][0]['value'],
  );

    $params['subject'] = t('!dedicant_name has made a donation !dedication_type of you', $replacement);
    $params['body'] = t(variable_get('crm_core_donation_imo_message', ''), $replacement);
    $params['bcc'] = '';

    drupal_mail('crm_core_profile_notification', 'crm_core_profile_notification', $dedicant_email, LANGUAGE_NONE, $params, variable_get('site_mail', NULL), TRUE);
}

/**
 * load available fields from the contact
 */
function crm_core_donation_fields($profile_name) {
  $crm_core_profile = crm_core_profile_load($profile_name);
  $fields = $crm_core_profile['fields'];
  $data = array();
  foreach ($fields['toggle'] as $_field => $toggle) {
    if ($toggle !== 0) {
      // need to get the label for the field
      $info = field_info_instance('crm_core_contact', $_field, $crm_core_profile['bundle_type']);
      $data[$_field] = $info['label'];
    }
  }

  return $data;
}

/**
 * Theme preprocessing function
 */
function crm_core_donation_form_theme_preprocess(&$variables) {
  drupal_add_css(drupal_get_path('module', 'crm_core_donation') . '/crm_core_donation.css');
  drupal_add_js(drupal_get_path('module', 'crm_core_donation') . '/crm_core_donation.js');

  $form = $variables['form'];

  // load the profile and get the contact fields
  $crm_core_profile = crm_core_profile_load($form['profile_name']['#value']);
  $fields = $crm_core_profile['fields'];
  $contact_fields = array();
  foreach ($fields['toggle'] as $field_name => $toggle) {
    if ($toggle !== 0) {
      $contact_fields[] = $field_name;
    }
  }

  $variables['payment_method'] = drupal_render($form['payment_method']);

  $variables['message'] = drupal_render($form['message']);
  $variables['header'] = drupal_render($form['header']);
  //  $form['activity']['field_donation_amounts']['#access'] = FALSE;
  //  $form['activity']['field_donation_dedication_type']['#access'] = FALSE;
  //  $form['activity']['field_donation_dedication_name']['#access'] = FALSE;
  //  $form['activity']['field_donation_dedication_email']['#access'] = FALSE;
  $amount_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Donation amount',
    '#children' => drupal_render($form['activity']['field_donation_amounts']),
  );
  $variables['amount'] = drupal_render($amount_field_set);

  // dedication
  $dedication = drupal_render($form['activity']['field_donation_dedication_type']);
  // $dedication = drupal_render($form['field_donation_dedication_type']);
  $dedication .= '<div id="dedication_info">';
  $dedication .= drupal_render($form['activity']['field_donation_dedication_name']);
  // $dedication .= drupal_render($form['field_donation_dedication_name']);
  $dedication .= drupal_render($form['activity']['field_donation_dedication_email']);
  $dedication .= drupal_render($form['field_donation_dedication_email']);
  $dedication .= '</div>';

  $dedication_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Dedication',
    '#children' => $dedication,
  );

  $variables['dedication'] = drupal_render($dedication_field_set);

  // billing information
  $contact ='';
  if (!empty($contact_fields)) {
    foreach ($contact_fields as $field) {
      $contact .= drupal_render($form[$field]);
    }
  }

  $contact_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Billing Information',
    '#children' => $contact,
  );

  $variables['billing'] = drupal_render($contact_field_set);

  // payment information
  $payment_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Payment Information',
    '#children' => drupal_render($form['commerce_payment']),
  );

  $variables['payment'] = drupal_render($payment_field_set);

  // remains
  $variables['submit'] = drupal_render($form['submit']);
  $variables['footer'] = drupal_render($form['footer']);
  $variables['rest'] = drupal_render_children($form);

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function crm_core_donation_form_crm_core_profile_entry_form_alter(&$form, &$form_state, $form_id) {
  // adding additional classes
  $profile = $form_state['profile'];

  // making sure we are on the correct profile
  if ($profile['name'] != variable_get('crm_core_donation_profile', '')) {
    return;
  }
  if (empty($form['#attributes']['class'])) {
    $form['#attributes']['class'] = array('crm_core_donation_form');
  }
  else {
    $form['#attributes']['class'] += array('crm_core_donation_form');
  }

  $donation_page = $profile['donation_page'];
  $form_state['donation_page'] = $donation_page;
  if ($donation_page['title'] != '') {
    drupal_set_title($donation_page['title']);
  }

  if ($donation_page['pdp'] == 1) {
    $user = menu_get_object('user');
    if (!empty($user)) {
      $form['message'] = array(
        '#prefix' => '<div class="messages warning">',
        '#suffix' => '</div>',
        '#markup' => 'You can view your live donation page ' . l('here', 'donation_pages/' . $donation_page['id']),
      );
    }
  }

  $header = unserialize($donation_page['header']);
  $footer = unserialize($donation_page['footer']);
  $form['header'] = array(
    '#markup' => $header['value'],
  );

  $form['footer'] = array(
    '#markup' => $footer['value'],
  );

  // set campaign (the donation page id)
  $form['activity']['field_donation_campaign'][LANGUAGE_NONE][0]['value']['#default_value'] = $donation_page['id'];

  // preset an amount on the donation form according to get
  if (isset($form['activity']['field_donation_amounts'][LANGUAGE_NONE]['#options'])) {
    $amount_set = array_keys($form['activity']['field_donation_amounts'][LANGUAGE_NONE]['#options']);
    if (isset($_GET['amount'])) {
      if (in_array($_GET['amount'], $amount_set)) {
          $form['activity']['field_donation_amounts'][LANGUAGE_NONE]['#default_value']['value'] = check_plain($_GET['amount']);
      }
    }
  }

  // set amount
//  $amounts = unserialize($donation_page['amounts']);
//  if ($amounts != '') {
//     $_amounts = nl2br($amounts);
//     $_amounts = explode('<br />', $_amounts);
//     foreach($_amounts as $_amount) {
//       $_amount_options[(int)$_amount] = '$' . $_amount; //t('$%amount', array('%amount' => $_amount));
//     }
//     $form['activity']['field_donation_amounts'][LANGUAGE_NONE]['#default_value']['value'] = $_amounts[0];
//     $form['activity']['field_donation_amounts'][LANGUAGE_NONE]['#options'] = $_amount_options;
//  }

  $checkout_pane = commerce_checkout_panes(array('pane_id' => 'commerce_payment'));
  $checkout_pane = array_pop($checkout_pane);

  $form_state['checkout_pane'] = $checkout_pane;

  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.checkout_pane');

  //attach an order if it was not attached before
  if (!isset($form_state['order'])) {
    global $user;
    $order = commerce_order_new($user->uid, 'checkout_checkout');
    // attach some data to order obj so we can recognize the order as a related to crm_core_donation
    $order->data['crm_core_donation']['donation_page']['id'] = $form_state['profile']['donation_page']['id'];
    $form_state['order'] = $order;
  }
  else {
    $order = $form_state['order'];
  }

  // set default payment method for the donation page
  $data = unserialize($donation_page['data']);
  if (!empty($data)) {
    if (array_key_exists('payment_method', $data)) {
      if ($data['payment_method'] != '') {
        // detect the payment method and display some notification to the user
        $payment = explode('|', $data['payment_method']);
        if ($payment[0] == 'commerce_payment_example') {
          $link = l('click here', 'admin/commerce/config/payment-methods');
          $form['payment_method'] = array(
            '#markup' => "Currently the donation page is using an example payment method, please {$link} to set up.",
            '#prefix' => '<div class="messages warning">',
            '#suffix' => '</div>',
          );
        }
        $order->data['payment_method'] = $data['payment_method'];
      }
    }
  }

  $form['commerce_payment'] = commerce_payment_pane_checkout_form($form, $form_state, $checkout_pane, $order);

  $form['commerce_payment']['#tree'] = TRUE;

  $form['submit']['#value'] = t('donate');

  $form['#theme'] = 'crm_core_donation';
  $form['#validate'][] = 'crm_core_donation_form_validate';
  $form['#submit'][] = 'crm_core_donation_form_submit';

}


function crm_core_donation_form_validate($form, &$form_state) {
  // save an order if it was not saved before
  if (!empty($form_state['order']->order_id)) {
    $order = $form_state['order'];
  }
  else {
    $order = $form_state['order'];
    commerce_order_save($order);
  }

  // renew lineitems if amount is set
  if (isset($form_state['values']['field_donation_amounts'])) {
    $amount = $form_state['values']['field_donation_amounts'][LANGUAGE_NONE][0]['value'] * 100;
  }
  elseif (isset($form_state['values']['activity']['field_donation_amounts'])) {
    $amount = $form_state['values']['activity']['field_donation_amounts'][LANGUAGE_NONE][0]['value'] * 100;
  }
  if (!empty($amount)) {
    // delete all line items from the order that accidentally trap to order
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $old_line_items_ids = array();
    foreach ($order_wrapper->commerce_line_items as $item) {
      $value = $item->value();
      if (!empty($value)) {
        $old_line_items_ids[] = $value->line_item_id;
      }
    }
    commerce_line_item_delete_multiple($old_line_items_ids);
    unset($order->commerce_line_items);
    commerce_order_save($order);

    // create and attach a new one line item
    $line_item = _crm_core_donation_line_item_new($amount, $order->order_id);
    commerce_line_item_save($line_item);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $order_wrapper->commerce_line_items[] = $line_item;
    commerce_order_save($order);
  }

  $form_state['order'] = $order;

  // call payment method validator
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.checkout_pane');
  return commerce_payment_pane_checkout_form_validate($form, $form_state, $form_state['checkout_pane'], $order);
}

function crm_core_donation_form_submit($form, &$form_state) {

  if (isset($form_state['values']['commerce_payment']['payment_details']['credit_card'])) {
    $credit_card = $form_state['values']['commerce_payment']['payment_details']['credit_card'];
  }

  // attach to order contact, donation page and activity id's
  $form_state['order']->data['crm_core_donation']['contact']['contact_id'] = $form_state['contact']->contact_id;
  $form_state['order']->data['crm_core_donation']['donation_page_submission_activity']['activity_id'] =
    $form_state['crm_core_activity']->activity_id;
  $order = $form_state['order'];

  // create and attach commerce_customer profile to an order
  _crm_core_donation_commerce_attach_profile($order, $form_state);

  // fill a created activity with a values
  $activity_id = $form_state['crm_core_activity']->activity_id;
  $activity = crm_core_activity_load($activity_id);
  // add last 4 cc
  if (isset($credit_card)) {
    $activity->field_donation_cc_last4[LANGUAGE_NONE][0]['value'] = trim(drupal_substr(trim($credit_card['number']), -4));
  }
  // set order reference back to the activity
  $activity->field_donation_order[LANGUAGE_NONE][0]['target_id'] = $order->order_id;
  $activity->field_donation_order[LANGUAGE_NONE][0]['target_type'] = 'commerce_order';
  // populate activity participants field
  $activity->field_activity_participants[LANGUAGE_NONE][0]['target_id'] = $form_state['contact']->contact_id;
  $activity->field_activity_participants[LANGUAGE_NONE][0]['target_type'] = 'crm_core_contact';

  $recurring_payment_method = $form_state['values']['commerce_payment']['payment_method'] == 'authnet_arb|commerce_payment_authnet_arb';

  // call a payment method
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.checkout_pane');
  commerce_payment_pane_checkout_form_submit($form, $form_state, $form_state['checkout_pane'], $order);

  $form_state['order'] = $order;

  if ($form_state['rebuild'] == FALSE) {
    // save an order and update the order status to completed because the order has been processed
    if (!$recurring_payment_method) {
      commerce_order_status_update($order, 'checkout_complete');
    }

    // set an activity status
    if ($recurring_payment_method) {
      $activity->field_donation_status[LANGUAGE_NONE][0]['value'] = 'refund';
    }
    else {
      $activity->field_donation_status[LANGUAGE_NONE][0]['value'] = 'complete';
    }
    // show the message and redirect
    $form_state['redirect'] = $form_state['donation_page']['redirect'];
    drupal_set_message(variable_get('crm_core_donation_redirect_message', 'Thank you for your donation'));
  }
  else {
    // set a declined activity status
    $activity->field_donation_status[LANGUAGE_NONE][0]['value'] = 'declined';
  }

  $form_state['order'] = $order;
  commerce_order_save($order);
  crm_core_activity_save($activity);

}

/**
 * Create/Save a commerce_order
 */
function _crm_core_donation_commerce_order_save($amount, $user) {

 // Create the new order in checkout; you might also check first to
  // see if your user already has an order to use instead of a new one.
  $order = commerce_order_new($user->uid, 'checkout_checkout');

  commerce_order_save($order);

  $line_item = _crm_core_donation_line_item_new($amount, $order->order_id);

  commerce_line_item_save($line_item);

  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_wrapper->commerce_line_items[] = $line_item;

  commerce_order_save($order);

  return $order;
}

/**
 * Create a new custom line item
 */
function _crm_core_donation_line_item_new($amount, $order_id = 0, $currency_code = 'USD') {
  $type = 'crm_core_donation';

  // Create the new line item.
  $line_item = entity_create('commerce_line_item', array(
    'type' => $type,
    'order_id' => $order_id,
    'quantity' => 1,
  ));

  $line_item->commerce_unit_price = array(
    LANGUAGE_NONE => array(
      '0' => array(
        'amount' => $amount,
        'currency_code' => $currency_code,
      ),
    )
  );

  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

  if (!is_null($line_item_wrapper->commerce_unit_price->value())) {
    if (!commerce_price_component_load($line_item_wrapper->commerce_unit_price->value(), 'base_price')) {
      $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
        $line_item_wrapper->commerce_unit_price->value(),
        'base_price',
        $line_item_wrapper->commerce_unit_price->value(),
        TRUE
      );
    }
  }
  // Return the line item.
  return $line_item;
}

function _crm_core_donation_line_item_configuration($line_item_type) {
  $type = $line_item_type['type'];
}

function _crm_core_donation_line_item_title($line_item) {
  return t('Donation');
}

function _crm_core_donation_line_item_add_form($element, &$form_state) {
  $form = array();
  return $form;
}

function _crm_core_donation_line_item_add_form_submit(&$line_item, $element, &$form_state, $form) {
  $line_item->line_item_label = t('Donation');
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

  // Provide a default price.
  $amount = 10;
  $currency_code = 'USD';

  $line_item->commerce_unit_price = array('und' => array(
    '0' => array(
      'amount' => $amount,
      'currency_code' => $currency_code)
  ));

  if (!is_null($line_item_wrapper->commerce_unit_price->value())) {
    // Add the base price to the components array.
    if (!commerce_price_component_load($line_item_wrapper->commerce_unit_price->value(), 'base_price')) {
      $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
        $line_item_wrapper->commerce_unit_price->value(),
        'base_price',
        $line_item_wrapper->commerce_unit_price->value(),
        TRUE
      );
    }
  }
}

/**
 * Creates a commerce_customer profile and attach it to the passed order object
 *
 * @param object order
 *   a commerce order object
 *
 * @param array form_state
 *   a form_state array of crm_core_donation_form form
 *
 * @return object profile
 *   returns created profile object or FALSE
 */
function _crm_core_donation_commerce_attach_profile(&$order, $form_state) {
  // ToDo: both commerce_profile and activity are fieldable entities,
  //   so this code have be revorked to support configured fields.
  // But because we don't know the mapping, the current hardcoded solution is
  //   probably the best on this point.
  // Seems like we have a question to arhitecture here, how to sync commerce profiles and activities.

  // hardcoded profile name we are using here
  $profile_type = 'billing';

  $profile_info = commerce_customer_profile_type_load($profile_type);
  if (empty($profile_info)) {
    return FALSE;
  }

  // create a new profile, fill it with values and save
  $profile = commerce_customer_profile_new($profile_info['type'], $order->uid);
  $profile->entity_context = array(
    'entity_type' => 'commerce_order',
    'entity_id' => $order->order_id,
  );
  $profile->status = TRUE;
  $profile->uid = $order->uid;
  if ($profile_info['addressfield']) {
    $billing_address_field = variable_get('crm_core_donation_billing_address', '');
    $address = $form_state['values'][$billing_address_field][LANGUAGE_NONE][0];
    $profile->commerce_customer_address[LANGUAGE_NONE][0] = $address;
  }
  $contact_name = (empty($form_state['values']['contact_name'][LANGUAGE_NONE][0]['safe'])) ?
    $form_state['values']['contact_name'][LANGUAGE_NONE][0]
    : $form_state['values']['contact_name'][LANGUAGE_NONE][0]['safe'];
  $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] = implode(' ', $contact_name);
  commerce_customer_profile_save($profile);

  // attach created profile to order using a entity_wrapper
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_wrapper->{$profile_info['module'] . '_' . $profile_type} = $profile;

  return $profile;
}

/*
 * Implement a hook_authnet_arb_silentpost
 */
function crm_core_donation_authnet_arb_silentpost($post) {

  // init some variables
  $order_id = $post['x_po_num'];
  $order = commerce_order_load($order_id);
  $donation_page_submission_activity = crm_core_activity_load(
    $order->data['crm_core_donation']['donation_page_submission_activity']['activity_id']);

  if ($donation_page_submission_activity->type != 'donation') {
    return;
  }

  $amount = $post['x_amount']*100;
  $card_4cc = drupal_substr($post['x_account_number'], -4);
  $responce_code = $post['x_response_code'];

  // create a new activity
  // *** Create and save an activity ***
  module_load_include('inc', 'crm_core_donation', 'crm_core_donation.pages');
  $donation_page = crm_core_donation_page_load($order->data['crm_core_donation']['donation_page']['id']);
  $activity = array('type' => 'donation', 'title' => $donation_page['name']);
  $activity = crm_core_activity_create($activity);
  // populate activity fields with values from attached to order profile
  $crm_core_profile = variable_get('crm_core_donation_profile', '');
  $donation_activity_profile = crm_core_profile_activity_load($crm_core_profile);
  $donation_activity_profile_fields = $donation_activity_profile['fields'];
  $activity_fields_to_copy = array_filter($donation_activity_profile_fields['toggle']);

  foreach ($activity_fields_to_copy as $fieldname) {
    $activity->{$fieldname} = $donation_page_submission_activity->{$fieldname};
  }
  // populate activity participants field
  $activity->field_activity_participants[LANGUAGE_NONE][0]['target_id'] =
    $order->data['crm_core_donation']['contact']['contact_id'];
  $activity->field_activity_participants[LANGUAGE_NONE][0]['target_type'] = 'crm_core_contact';
  // populate activity order field
  $activity->field_donation_order[LANGUAGE_NONE][0]['target_id'] = $order->order_id;
  $activity->field_donation_order[LANGUAGE_NONE][0]['target_type'] = 'commerce_order';
  // populate activity last 4 cc field
  $activity->field_donation_cc_last4[LANGUAGE_NONE][0]['value'] = $card_4cc;
  // populate activity uid field
  global $user;
  $activity->uid =  $user->uid;
  // populate donation_campaign field
  $activity->field_donation_campaign[LANGUAGE_NONE][0]['value'] = $order->data['crm_core_donation']['donation_page']['id'];


  if ($responce_code == 1) {
    // if the recurring transaction was success

    // *** add a new one another line item to the order
    $order = commerce_order_load($order_id);
    $line_item = _crm_core_donation_line_item_new($amount, $order_id);
    commerce_line_item_save($line_item);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $order_wrapper->commerce_line_items[] = $line_item;
    commerce_order_save($order);

    // set an activity status to 'complete'
    $activity->field_donation_status[LANGUAGE_NONE][0]['value'] = 'complete';
  }
  else {
    // set an activity status to 'declined'
    $activity->field_donation_status[LANGUAGE_NONE][0]['value'] = 'declined';
  }

  // save an activity
  crm_core_activity_save($activity);

}

/**
 * Theming function for the main donation form
 * @todo: this will have to be converted to a preprocess function so we can use template
 * @depcreated: using a template right now
 */
function crm_core_donation_form_theme($variables) {

  $form = $variables['form'];
  // load the profile and get the contact fields
  $crm_core_profile = crm_core_profile_load($form['profile_name']['#value']);
  $fields = $crm_core_profile['fields'];
  $contact_fields = array();
  foreach ($fields['toggle'] as $field_name => $toggle) {
    if ($toggle !== 0) {
      $contact_fields[] = $field_name;
    }
  }
  $output = '';

  $output .= drupal_render($form['message']);

  $output .= '<div id="donation_header">';
  $output .= drupal_render($form['header']);
  $output .= '</div>';

  // amounts
  $output .= '<div id="amounts">';

  $amount_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Donation amount',
    '#children' => drupal_render($form['activity']['field_donation_amounts']),
  );

  $output .= drupal_render($amount_field_set);

  $output .= '</div>';

  // dedication
  $output .= '<div id="dedication">';
  $dedication = drupal_render($form['activity']['field_donation_dedication_type']);

  $dedication .= '<div id="dedication_info">';
  $dedication .= drupal_render($form['activity']['field_donation_dedication_name']);
  $dedication .= drupal_render($form['activity']['field_donation_dedication_email']);
  $dedication .= '</div>';

  $dedication_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Dedication',
    '#children' => $dedication,
  );

  $output .= drupal_render($dedication_field_set);

  $output .= '</div>';

  // contact information
  $output .= '<div id="billing">';
  $contact ='';
  if (!empty($contact_fields)) {
    foreach ($contact_fields as $field) {
      $contact .= drupal_render($form[$field]);
    }
  }

  $contact_field_set = array(
    '#type' => 'fieldset',
    '#title' => 'Billing Information',
    '#children' => $contact,
  );

  $output .= drupal_render($contact_field_set);

  $output .= '</div>';

  // payment information
  $output .= '<div id="payment">';
  $output .= drupal_render($form['payment']);
  $output .= '</div>';

  $output .= drupal_render($form['submit']);

  $output .= '<div id="donation_footer">';
  $output .= drupal_render($form['footer']);
  $output .= '</div>';

  // $output .= drupal_render($form['submit']);
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Implements hook_views_data().
 */
function crm_core_donation_views_data() {
  $data = array();

  $data['crm_core_donation_page']['table']['group'] = t('CRM Donation');
  $data['crm_core_donation_page']['table']['base'] = array(
    'field' => 'id',
    'title' => t('CRM Core Donation Page'),
    'help' => t('The donation page'),
  );

  $data['crm_core_donation_page']['id'] = array(
    'title' => t('Donation page ID'),
    'help' => t('The unqiue internal identifier for a donation page'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
    ),
  );

  $data['crm_core_donation_page']['title'] = array(
    'title' => t('Donation page title'),
    'help' => t('Title of the donation page'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['crm_core_donation_page']['title'] = array(
    'title' => t('Donation page title'),
    'help' => t('Title of the donation page'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['crm_core_donation_page']['path'] = array(
    'title' => t('Path'),
    'help' => t('The site path to the donation page'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['crm_core_donation_page']['header'] = array(
    'title' => t('Header'),
    'help' => t('The donation page header message'),
    'field' => array(
      'handler' => 'views_handler_field_text_format',
      'click sortable' => FALSE,
    ),
  );

  $data['crm_core_donation_page']['status'] = array(
    'title' => t('Status'),
    'help' => t('Status of a donation page'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
    ),
  );

  $data['crm_core_donation_page']['uid'] = array(
    'title' => t('Donation Page Owner'),
    'help' => t('User UID of the donation page owner'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric.inc',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
    ),
   'relationship' => array(
      'handler' => 'views_handler_relationship',
      'base' => 'users',
      'field' => 'uid',
      'label' => t('Donation page creator'),
    ),
  );

  $data['crm_core_donation_page']['pdp'] = array(
    'title' => t('Personal donation page'),
    'help' => t('If this is a personal donation page'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
    ),
  );


  $data['crm_core_donation_page']['created'] = array(
    'title' => t('Created date'),
    'help' => t('The date the donation page was created'),
    'field' => array(
      'handler' => 'views_handler_field_date',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort_date',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_date',
    ),
  );

  return $data;
}
